"""Pydantic schemas for agent inputs and outputs."""

from product_research.schemas.models import (
    ValidationImageExtractionAgentSchema,
    ValidationImageExtractionAgentSchema__Product,
    ValidationImageExtractionAgentSchema__ValidatedPagesItem,
    FilterAgentSchema,
    SearchAgentBarcodeGoogleSchema,
    SearchAgentBarcodeGoogleSchema__ResultsItem,
    SearchAgentBarcodeYahooSchema,
    SearchAgentBarcodeYahooSchema__ResultsItem,
    SearchAgentBarcodeOpenaiSchema,
    SearchAgentBarcodeOpenaiSchema__ResultsItem,
    SearchAgentSkuGoogleSchema,
    SearchAgentSkuGoogleSchema__ResultsItem,
    SearchAgentSkuYahooSchema,
    SearchAgentSkuYahooSchema__ResultsItem,
    SearchAgentSkuOpenaiSchema,
    SearchAgentSkuOpenaiSchema__ResultsItem,
    SearchAgentTitleSkuGoogleSchema,
    SearchAgentTitleSkuGoogleSchema__ResultsItem,
    SearchAgentAllFieldsOpenaiSchema,
    SearchAgentAllFieldsOpenaiSchema__ItemsItem,
    ProductInput,
    BatchResult,
    BatchJobResponse,
)

__all__ = [
    "ValidationImageExtractionAgentSchema",
    "ValidationImageExtractionAgentSchema__Product",
    "ValidationImageExtractionAgentSchema__ValidatedPagesItem",
    "FilterAgentSchema",
    "SearchAgentBarcodeGoogleSchema",
    "SearchAgentBarcodeGoogleSchema__ResultsItem",
    "SearchAgentBarcodeYahooSchema",
    "SearchAgentBarcodeYahooSchema__ResultsItem",
    "SearchAgentBarcodeOpenaiSchema",
    "SearchAgentBarcodeOpenaiSchema__ResultsItem",
    "SearchAgentSkuGoogleSchema",
    "SearchAgentSkuGoogleSchema__ResultsItem",
    "SearchAgentSkuYahooSchema",
    "SearchAgentSkuYahooSchema__ResultsItem",
    "SearchAgentSkuOpenaiSchema",
    "SearchAgentSkuOpenaiSchema__ResultsItem",
    "SearchAgentTitleSkuGoogleSchema",
    "SearchAgentTitleSkuGoogleSchema__ResultsItem",
    "SearchAgentAllFieldsOpenaiSchema",
    "SearchAgentAllFieldsOpenaiSchema__ItemsItem",
    "ProductInput",
    "BatchResult",
    "BatchJobResponse",
]
